# Generated by Django 5.2 on 2025-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=100)),
                ('flag', models.URLField()),
                ('region', models.CharField(max_length=100)),
                ('languages', models.JSONField()),
            ],
        ),
    ]
